### PR TITLE
LinuxEmulation: Minor cleanup by separating VMA definitions

### LINKED ISSUE #4557: `VMA Tracking corruption` is a vengeful spirit
I have been getting hit by this hard recently. It seems to occur fairly frequently with Steam when it is hammering a big game download.
In my case I'm hitting it with `Spider-Man 2` quite consistently.

Backtrace:
```
#0  FEXCore::Assert::ForcedAssert () at /mnt/Work/Work/work/FEXNew/FEXCore/Source/Utils/ForcedAssert.cpp:9
9         asm volatile("hlt #1");
[Current thread is 1 (Thread 0xc1438cc0 (LWP 72746))]
(gdb) bt
#0  FEXCore::Assert::ForcedAssert () at /mnt/Work/Work/work/FEXNew/FEXCore/Source/Utils/ForcedAssert.cpp:9
#1  0x0000aaaae53d8be0 in LogMan::Throw::MFmt (fmt=<optimized out>, args=...) at /mnt/Work/Work/work/FEXNew/FEXCore/Source/Utils/LogManager.cpp:29
#2  0x0000aaaae52dd964 in LogMan::Throw::AFmt<>(bool, char const*) (Value=<optimized out>, fmt=<optimized out>) at /mnt/Work/Work/work/FEXNew/FEXCore/include/FEXCore/Utils/LogManager.h:53
#3  FEX::HLE::SyscallHandler::TrackMremap (this=0xffff94622000, Thread=0x48e88b000, OldAddress=3100446720, OldSize=<optimized out>, NewSize=<optimized out>, flags=1, NewAddress=2937729024) at /mnt/Work/Work/work/FEXNew/Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp:283
#4  0x0000aaaae52ea724 in FEX::HLE::x32::RegisterMemory(FEX::HLE::SyscallHandler*)::$_4::operator()(FEXCore::Core::CpuStateFrame*, void*, unsigned long, unsigned long, int, void*) const (Frame=0x48e88b0a0, old_address=0xb8cd1000, old_size=806912, new_size=1052672, flags=1, new_address=<optimized out>, this=<optimized out>) at /mnt/Work/Work/work/FEXNew/Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Memory.cpp:95
#5  FEX::HLE::x32::RegisterMemory(FEX::HLE::SyscallHandler*)::$_4::__invoke(FEXCore::Core::CpuStateFrame*, void*, unsigned long, unsigned long, int, void*) (Frame=0x48e88b0a0, old_address=0xb8cd1000, old_size=806912, new_size=1052672, flags=1, new_address=<optimized out>) at /mnt/Work/Work/work/FEXNew/Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Memory.cpp:95
#6  0x00000005f53f3ecc in ?? ()
#7  0x000000048e882000 in ?? ()
#8  0x0001010000000100 in ?? ()
```

Without assertions enabled it of course just results in a crash.

Once the game is downloaded, it seems fine enough. The `ThreadedValidation` step doesn't seem to cause problems.

This bug has also been around for a few months, so it's not a recent regression.

### PR DESCRIPTION
**Pull request by Sonicadvance1**
NFC, just moving this to its own header. It's already a huge PITA to read. I just want to try and preserve some sanity while attempting to fix #4557

### CODE REVIEW

File: Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsVMATracking.h [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+#include <FEXCore/Utils/SignalScopeGuards.h>
+
+namespace FEXCore::IR {
+struct AOTIRCacheEntry;
+}
+
+namespace FEX::HLE::VMATracking {
+///// VMA (Virtual Memory Area) tracking /////
+
+struct SpecialDev {
```
Comment (lioncash) [inline Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsVMATracking.h:17]: This is pre-existing since the previous code, but is this intended to be a namespace rather than a struct?

Comment (Sonicadvance1) [reply Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsVMATracking.h:17]: Probably?

Comment (Sonicadvance1) [reply Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsVMATracking.h]: switched it to a namespace.

**Review by lioncash — APPROVED** [review]
