### PR TITLE
FEXCore: Implement support for NX bit.

### LINKED ISSUE #2175: Unvanquished: Crashes with error about DEP
**What Game**

Unvanquished, downloaded from https://unvanquished.net/download/

**Describe the bug**

Trying to launch Unvanquished fails because the `nacl_loader` process crashes.

**To Reproduce**

1. Download the launcher for Linux
2. Unzip and execute the launcher, install Unvanquished
3. Hit the button to start the game
4. See the crash

**Expected behavior**

The game should not crash.

**Screenshots and Video**

<details>

<summary>Logs:</summary>

```
ixn@jammy:/tmp$ ~/.local/share/unvanquished/base/daemon
Unvanquished 0.53.2 Linux x86_64 Sep  4 2022
cmdline:
[FS] Lib path: /home/ixn/.local/share/unvanquished/base 
[FS] Home path: /home/ixn/.local/share/unvanquished 
[FS] Pak search path: /home/ixn/.local/share/unvanquished/base/pkg 
[FS] Pak search path: /home/ixn/.local/share/unvanquished/pkg 
Starting crash logging server 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/unvanquished_0.53.2.dpk'... 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/unvanquished_0.52.0.dpk'... 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/tex-common_2.2.dpk'... 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/res-players_0.53.0.dpk'... 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/res-players_0.52.dpk'... 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/res-legacy_0.52.dpk'... 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/res-weapons_0.53.0.dpk'... 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/res-weapons_0.52.1.dpk'... 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/res-weapons_0.52.dpk'... 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/res-buildables_0.53.0.dpk'... 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/res-buildables_0.52.dpk'... 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/res-voices_0.52.dpk'... 
[FS] Loading pak '/home/ixn/.local/share/unvanquished/base/pkg/res-soundtrack_0.52.dpk'... 
execing 'default.cfg' 
execing 'presets/input/wasd.cfg' 
Warn: Couldn't read conhistory: No such file or directory 
----- Client Initialization ----- 
Loading RSA keys from pubkey 
Daemon RSA public-key found. 
----- Client Initialization Complete ----- 
IP: 127.0.0.1 
IP: 192.168.10.50 
IP: 192.168.10.100 
IP: 10.0.3.1 
IP6: ::1 
IP6: fe80::2ebd:a9a2:fa21:99c%enP4p65s0 
Opening IP6 socket: [::]:* 
Opening IP socket: 0.0.0.0:* 
--- Common Initialization Complete --- 
Calling GetRefAPI… 
SDL_Init( SDL_INIT_VIDEO )...  
Using SDL version 2.0.12 
SDL using driver "x11" 
Initializing OpenGL display 
Using GLEW version 2.2.0 
Display aspect: 1.250 
Display resolution: 1280x1024 
...setting mode -2: 1280×1024 
Using preferred context - 24-bit OpenGL 2.1 compatibility 
OpenGL Renderer: Mali-G610 (Panfrost) 
Warn: Provided OpenGL 3.0 is not the same as requested 2.1 version 
Using GL3 Renderer in OpenGL 2.x mode... 
Available modes: '1280x1024 320x240 800x600 1024x768 1152x864 1280x960 720x480 640x400 1280x800 864x486 1024x576 1280x720 720x400 640x350 ' 
Detected graphics driver class 'integrated' 
Detected graphics hardware class 'generic' 
Initializing OpenGL extensions 
...ignoring GL_ARB_debug_output 
...found shading language version 130 
...using GL_ARB_half_float_pixel 
...using GL_ARB_texture_float 
...using GL_EXT_gpu_shader4 
...using GL_EXT_texture_integer 
...using GL_ARB_texture_rg 
...using GL_ARB_texture_gather 
...using GL_EXT_texture_compression_s3tc 
...using GL_ARB_texture_compression_rgtc 
...using GL_EXT_texture_filter_anisotropic 
...using GL_ARB_half_float_vertex 
...using GL_ARB_framebuffer_object 
...using GL_ARB_get_program_binary 
...using GL_ARB_buffer_storage 
...using GL_ARB_uniform_buffer_object 
...using GL_ARB_map_buffer_range 
...using GL_ARB_sync 
GL_VENDOR: Panfrost 
GL_RENDERER: Mali-G610 (Panfrost) 
GL_VERSION: 3.0 Mesa 23.0.0-devel (git-fd340d5154) 
GL_MAX_TEXTURE_SIZE: 8192 
GL_SHADING_LANGUAGE_VERSION: 1.30 
GL_MAX_VERTEX_UNIFORM_COMPONENTS 16352 
GL_MAX_VERTEX_ATTRIBS 16 
Occlusion query bits: 64 
GL_MAX_DRAW_BUFFERS: 8 
GL_TEXTURE_MAX_ANISOTROPY_EXT: 16.000000 
GL_MAX_RENDERBUFFER_SIZE: 8192 
GL_MAX_COLOR_ATTACHMENTS: 8 
PIXELFORMAT: color(24-bits) 
MODE: -2, 1280 x 1024 fullscreen hz: N/A 
Using OpenGL version 3.0, requested: 2.1 
Using OpenGL 2.x context. 
Using OpenGL extensions: GL_ARB_half_float_pixel GL_ARB_texture_float GL_EXT_gpu_shader4 GL_EXT_texture_integer GL_ARB_texture_rg GL_ARB_texture_gather GL_EXT_texture_compression_s3tc GL_ARB_texture_compression_rgtc GL_EXT_texture_filter_anisotropic GL_ARB_half_float_vertex GL_ARB_framebuffer_object GL_ARB_get_program_binary GL_ARB_buffer_storage GL_ARB_uniform_buffer_object GL_ARB_map_buffer_range GL_ARB_sync 
Using S3TC (DXTC) texture compression. 
Using GPU vertex skinning with max 256 bones in a single pass, models are hardware accelerated. 
][ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
Extracting VM module cgame-x86_64.nexe from /home/ixn/.local/share/unvanquished/base/pkg/unvanquished_0.53.2.dpk...
 
Loading VM module cgame-x86_64.nexe... 
Using loader args:  /home/ixn/.local/share/unvanquished/base/nacl_helper_bootstrap /home/ixn/.local/share/unvanquished/base/nacl_loader --r_debug=0xXXXXXXXXXXXXXXXX --reserved_at_zero=0xXXXXXXXXXXXXXXXX -v -B /home/ixn/.local/share/unvanquished/base/irt_core-x86_64.nexe -e -i 100:45 -- /home/ixn/.local/share/unvanquished/cgame-x86_64.nexe 100 
Warn: Error during initialization: IPC: Socket closed by remote end 
Error during cgame shutdown: IPC: Failed to send message: Broken pipe 
Warn: VM exited with non-zero exit code 2
 
ixn@jammy:/tmp$ /home/ixn/.local/share/unvanquished/base/nacl_helper_bootstrap /home/ixn/.local/share/unvanquished/base/nacl_loader --r_debug=0xXXXXXXXXXXXXXXXX --reserved_at_zero=0xXXXXXXXXXXXXXXXX -v -B /home/ixn/.local/share/unvanquished/base/irt_core-x86_64.nexe -e -i 100:45 -- /home/ixn/.local/share/unvanquished/cgame-x86_64.nexe 100
sel_ldr argument list:
/home/ixn/.local/share/unvanquished/base/nacl_loader --r_debug=0x0000000000213000 --reserved_at_zero=0x0000000000000000 -v -B /home/ixn/.local/share/unvanquished/base/irt_core-x86_64.nexe -e -i 100:45 -- /home/ixn/.local/share/unvanquished/cgame-x86_64.nexe 100
[48090,2293663616:21:20:52.368948] Error while loading "/home/ixn/.local/share/unvanquished/cgame-x86_64.nexe": Data Execution Prevention is required but is not supported
[48090,2293663616:21:20:52.397326] NaClPerfCounterInterval(SelMain __start__:SnapshotBlob): 49539 microsecs
[48090,2293663616:21:20:52.400980] NACL: Application output follows
[48090,2293663616:21:20:52.401246] NaClAppStartModule: module not loaded
Dumping vmmap.
In PrintVmmap
Done.
```

The important line appears to be this:

`[48090,2293663616:21:20:52.368948] Error while loading "/home/ixn/.local/share/unvanquished/cgame-x86_64.nexe": Data Execution Prevention is required but is not supported`

</details>

**System information:**
 - OS: Ubuntu 22.04 in bubblewrap container
 - CPU/SoC: Rockchip RK3588
 - Video driver version: OpenGL 3.0 Mesa 23.0.0-devel (git-fd340d5154), with ARM assembly patched out
 - RootFS used: Ubuntu 22.04 Official Rootfs
 - FEX version: FEX-2211-2-g5336f01
 - Thunks Enabled: No

**Additional context**
 - Is this an x86 or x86-64 game: x86-64
 - Does this reproduce on x86-64 host with FEX: Untested
 - Does this reproduce on AArch64 with Radeon/Intel/Nvidia: Untested
 - Is this a Vulkan game: No

The check for DEP appears to be here:

https://source.chromium.org/chromium/chromium/src/+/main:native_client/src/trusted/platform_qualify/posix/nacl_dep_qualify.c;l=147;drc=c3304aefc16d3c021c637ea6edfd9a8ab750a2db

### PR DESCRIPTION
**Pull request by Sonicadvance1**
Long time coming but thanks to bylaw's changes in #4474, this is now trivial to implement.

Fixes #2175

### CODE REVIEW

File: FEXCore/Source/Interface/Core/Frontend.cpp [hunk 1]
```diff
@@ -1321,7 +1321,7 @@ void Decoder::DecodeInstructionsAtEntry(const uint8_t* _InstStream, uint64_t PC,
       BlockIt->Size += DecodeInst->InstSize;
 
       // Can not continue this block at all on invalid instruction
-      if (BlockIt->HasInvalidInstruction) [[unlikely]] {
+      if (BlockIt->BlockStatus != DecodedBlockStatus::SUCCESS) [[unlikely]] {
```
Comment (bylaws) [inline FEXCore/Source/Interface/Core/Frontend.cpp:1324]: Could you update the print below on ln 1334 to print a different message in both cases?

Comment (Sonicadvance1) [reply FEXCore/Source/Interface/Core/Frontend.cpp:1324]: Sure, updated the message.
