### PR TITLE
Linux: Fixes 32-bit mmap

### LINKED ISSUE #1630: Kega fusion fails to map memory
Looks like Kega Fusion does some allocating that breaks under FEX for some reason.
mmap return EINVAL and early exiting. Probably something simple.

### PR DESCRIPTION
**Pull request by Sonicadvance1**
This went unnoticed for so long since most applications are new enough
to use mmap2 instead of mmap.
This was just completely broken.

Fixes #1630

### CODE REVIEW

File: Source/Tests/LinuxSyscalls/x32/Memory.cpp [hunk 1]
```diff
@@ -26,18 +26,26 @@ static std::string get_fdpath(int fd)
...
-    REGISTER_SYSCALL_IMPL_X32(mmap, [](FEXCore::Core::CpuStateFrame *Frame, uint32_t addr, uint32_t length, int prot, int flags, int fd, int32_t offset) -> uint64_t {
+    struct old_mmap_struct {
+      uint32_t addr;
+      uint32_t len;
+      uint32_t prot;
+      uint32_t flags;
+      uint32_t fd;
+      uint32_t offset;
+    };
+    REGISTER_SYSCALL_IMPL_X32(mmap, [](FEXCore::Core::CpuStateFrame *Frame, old_mmap_struct *const arg) -> uint64_t {
```
Comment (skmp) [inline Source/Tests/LinuxSyscalls/x32/Memory.cpp:37]: Shouldn't this be `const old_mmap_struct * arg` ? (const data, not const pointer?)

**Review by skmp — APPROVED** [review]

File: Source/Tests/LinuxSyscalls/x32/Memory.cpp (hunk 1 above)
Comment (Sonicadvance1) [reply Source/Tests/LinuxSyscalls/x32/Memory.cpp]: Oops yes, fixed.
