### PR TITLE
Syscall cleanup

### LINKED ISSUE #12: Syscall emulation has incorrect global mutex
There is a scoped mutex at the top of the syscall handling function.
This is incorrect and causes the application to stall once threading kicks in.
Should be removed and only have a mutex on things that actually need it.
Can be done alongside syscall cleanup.

I think skmp wanted to have a go at this?

### PR DESCRIPTION
**Pull request by Sonicadvance1**
Splits out syscalls to more files and changes over to a jump table for handling the syscalls
Fixes a few bugs where we were missing checking errno returns.
Minor optimization where since we have syscall definitions we can optimize away the argument loading.
Until we have function calls in the IR we can't jump directly to the handler yet.
Fixes #12

### CODE REVIEW

File: External/FEXCore/Source/Interface/Core/Core.cpp [hunk 1]
```diff
@@ -126,7 +126,7 @@ namespace DefaultFallbackCore {
 namespace FEXCore::Context {
   Context::Context()
     : FrontendDecoder {this}
-    , SyscallHandler {this} {
+    , SyscallHandler {FEXCore::CreateHandler(64, this)} {
```
Comment (skmp) [inline External/FEXCore/Source/Interface/Core/Core.cpp:129]: what does `64` mean here?

File: External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp [hunk 2]
```diff
@@ -422,8 +420,10 @@ void *JITCore::CompileCode([[maybe_unused]] FEXCore::IR::IRListView<true> const
         uint64_t SPOffset = AlignUp((RA64.size() + 7 + 1) * 8, 16);
 
         sub(sp, sp, SPOffset);
-        for (uint32_t i = 0; i < 7; ++i)
+        for (uint32_t i = 0; i < 7; ++i) {
```
Comment (skmp) [inline External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp:423]: Why not `FEXCore::HLE::SyscallArguments::MAX_ARGS`?

File: External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp [hunk 3]
```diff
@@ -1359,14 +1351,18 @@ void *JITCore::CompileCode([[maybe_unused]] FEXCore::IR::IRListView<true> const
         auto Desired = GetSrc<RA_64>(Op->Header.Args[1].ID());
         auto MemSrc = GetSrc<RA_64>(Op->Header.Args[2].ID());
 
-        add(TMP1, MEM_BASE, MemSrc);
+        if (!CTX->Config.UnifiedMemory) {
```
Comment (skmp) [inline External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp:1354]: Do we support non-unified memory?

Design wise, wouldn't it be simpler to have membase as IR, and not in the backend?

File: External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp [hunk 4]
```diff
@@ -1781,32 +1784,31 @@ void *JITCore::CompileCode([[maybe_unused]] FEXCore::IR::IRListView<true> const
           // Result: RAX
 
           // These are pushed in reverse order because stacks
-          for (uint32_t i = 7; i > 0; --i)
+          for (uint32_t i = 7; i > 0; --i) {
```
Comment (skmp) [inline External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp:1787]: `FEXCore::HLE::SyscallArguments::MAX_ARGS`?

File: External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp (hunk 3 above)
Comment (Sonicadvance1) [reply External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp:1354]: Currently non-unified is required for the unit tests since they use a bunch of absolute addressing that causes issues with unified. Otherwise non-unified is effectively not implemented (Especially after this PR which strips it out of syscalls entirely)

**Comment by Sonicadvance1** [comment]
This now has a requirement on #84 to pass the unit tests

File: External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp (hunk 4 above)
Comment (Sonicadvance1) [reply External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp]: Did it

File: External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp (hunk 2 above)
Comment (Sonicadvance1) [reply External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp]: Did it

File: External/FEXCore/Source/Interface/Core/Core.cpp (hunk 1 above)
Comment (Sonicadvance1) [reply External/FEXCore/Source/Interface/Core/Core.cpp]: You're right. Was difficult to tell what it was doing there.
Switched over to an enum to know if operating in 32bit or 64bit mode.
32bit mode not implemented yet.
