### PR TITLE
ELFCodeLoader: Don't use std::random_device for RNG

### LINKED ISSUE #2095: std::random_device can fail!
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  random_device::random_device(const std::string&): device not available
```

We need to support a fallback path in this case, I didn't realize this was a possibility.

### PR DESCRIPTION
**Pull request by Sonicadvance1**
Fixes #2095

std::random_device can fail to find a random source and throw an assert during initialization.

The constructor allows you to provide a token string to select an explicit random source, but this is c++ library specific and will still assert if the source isn't found. Also specific tokens are very much target and library specific, so it is unsafe to use.

In the libstdc++ case, the default implementation will try to open `/dev/urandom` which might not be available on all targets.

Instead of relying on this C++ object, use the `getrandom` syscall directly to generate our RNG used in the ELFCodeLoader. Resolves any sort of asserting case, blocks on RNG generation, and is guaranteed to be available since this syscall has been available since a very old kernel version.

### CODE REVIEW

File: Source/Tests/ELFCodeLoader2.h [hunk 1]
```diff
@@ -472,9 +473,18 @@ class ELFCodeLoader2 final : public FEXCore::CodeLoader {
...
         constexpr uint64_t ASLR_BITS_64 = 28;
         constexpr uint64_t ASLR_BITS_32 = 8;
-        std::random_device rd;
-        std::uniform_int_distribution<uint64_t> d(0);
-        uint64_t ASLR_Offset = d(rd);
+        uint64_t ASLR_Offset{};
+        ssize_t Result{};
+        do {
+          // Use the getrandom syscall instead of std::random_device because std can assert.
+          // <256 bytes of RNG requested, guaranteed to not be interrupted by signal.
```
Comment (neobrain) [inline Source/Tests/ELFCodeLoader2.h:480]: Are these two unrelated facts, or does one imply the other? In the latter case I'd suggest:
```suggestion
          // This is guaranteed to not be interrupted by a signal,
          // since fewer than 256 bytes of RNG data are requested
```

File: Source/Tests/ELFCodeLoader2.h [hunk 2]
```diff
@@ -720,11 +730,18 @@ class ELFCodeLoader2 final : public FEXCore::CodeLoader {
...
     else {
       // Nothing provided from the kernel, generate our own random values.
-      std::random_device rd;
-      std::uniform_int_distribution<uint64_t> d(0);
-
-      RandomLoc[0] = d(rd);
-      RandomLoc[1] = d(rd);
+      ssize_t Result{};
+      do {
+        // Use the getrandom syscall instead of std::random_device because std can assert.
```
Comment (neobrain) [inline Source/Tests/ELFCodeLoader2.h:735]: Moving this to a file-local helper template function allows us to avoid duplicating this docstring.

**Review by neobrain — APPROVED** [review]

File: Source/Tests/ELFCodeLoader2.h (hunk 2 above)
Comment (Sonicadvance1) [reply Source/Tests/ELFCodeLoader2.h]: Switched to local helper.

File: Source/Tests/ELFCodeLoader2.h (hunk 1 above)
Comment (Sonicadvance1) [reply Source/Tests/ELFCodeLoader2.h]: Modified comment.
